version: 1.0.{build}
image: Visual Studio 2015
clone_folder: c:\projects\myproject
init:
- cmd: echo This is batch
environment:
  my_var1: value1
  my_var2: value 2
  matrix:
  - platform: x86
    configuration: Debug
install:
- ps: Write-Host 'This is PowerShell'
