name: BuildandTest

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 3.1.101
    - name: Setup Node
      uses: actions/setup-node@v1.1.0
    - run: npm install
    - name: Build with dotnet
      working-directory: ./core
      run: dotnet build --configuration Release
    - name: Run Tests
      working-directory: ./core
      run: dotnet test
